# QA pipeline at SonarSource
# Based on https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

TARGET_PLATFORM:
  - neon
  - oxygen
  - photon
  - 2019-06

SQ_VERSION:
  - LATEST_RELEASE[6.7]
  - LATEST_RELEASE[7.9]
  - LATEST_RELEASE
  - DOGFOOD

exclude:
  - TARGET_PLATFORM: neon
    SQ_VERSION: LATEST_RELEASE[7.9]
  - TARGET_PLATFORM: neon
    SQ_VERSION: LATEST_RELEASE
  - TARGET_PLATFORM: neon
    SQ_VERSION: DOGFOOD
  - TARGET_PLATFORM: oxygen
    SQ_VERSION: LATEST_RELEASE[6.7]
  - TARGET_PLATFORM: oxygen
    SQ_VERSION: LATEST_RELEASE
  - TARGET_PLATFORM: oxygen
    SQ_VERSION: DOGFOOD
  - TARGET_PLATFORM: photon
    SQ_VERSION: LATEST_RELEASE[6.7]
  - TARGET_PLATFORM: photon
    SQ_VERSION: LATEST_RELEASE[7.9]
  - TARGET_PLATFORM: photon
    SQ_VERSION: DOGFOOD
  - TARGET_PLATFORM: 2019-06
    SQ_VERSION: LATEST_RELEASE[6.7]
  - TARGET_PLATFORM: 2019-06
    SQ_VERSION: LATEST_RELEASE[7.9]
  - TARGET_PLATFORM: 2019-06
    SQ_VERSION: LATEST_RELEASE
