language: java
sudo: false
install: true

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TARGET=CI
    - TARGET=IT TARGET_PLATFORM=e43
    - TARGET=IT TARGET_PLATFORM=e44
    - TARGET=IT TARGET_PLATFORM=e45
    - TARGET=IT TARGET_PLATFORM=e46
    - TARGET=IT TARGET_PLATFORM=e47

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "pkYhgQj9XGypKetnqoYLBMUqFZdeEH4t22UciiEak44M5/6+jwJFhsSHL8htyv4P8xQforEwC6V0RKKvPb1UFLnWF0P235nHRDpTUMwAmIsEGAL/kMJlzVok4KDVmr77JKTVUehBIwAYV0gCM3j5bb7Oh1cZ24I+DI55zyEL7iw="
  on_start: always

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
