name: sonar-release
on:
  release:
    types:
      - published

jobs:
  sonar_release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v5
    with:
      publishToBinaries: true
      slack_channel: team-sonarlint-intelliclipse-notifs
